# Generated by Django 4.1.7 on 2023-03-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Soc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('link1', models.URLField(blank=True, verbose_name='link1')),
                ('name_link1', models.CharField(blank=True, max_length=100, verbose_name='name link1')),
                ('link2', models.URLField(blank=True, verbose_name='link2')),
                ('name_link2', models.CharField(blank=True, max_length=100, verbose_name='name link2')),
                ('link3', models.URLField(blank=True, verbose_name='link3')),
                ('name_link3', models.CharField(blank=True, max_length=100, verbose_name='name link3')),
                ('link4', models.URLField(blank=True, verbose_name='link4')),
                ('name_link4', models.CharField(blank=True, max_length=100, verbose_name='name link4')),
            ],
        ),
    ]
