# Generated by Django 4.1.7 on 2023-03-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_soc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soc',
            name='name',
        ),
        migrations.AddField(
            model_name='soc',
            name='adress',
            field=models.CharField(blank=True, max_length=100, verbose_name='adress'),
        ),
        migrations.AddField(
            model_name='soc',
            name='company',
            field=models.CharField(blank=True, max_length=50, verbose_name='company'),
        ),
        migrations.AddField(
            model_name='soc',
            name='country',
            field=models.CharField(blank=True, max_length=50, verbose_name='country'),
        ),
        migrations.AddField(
            model_name='soc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AddField(
            model_name='soc',
            name='fax',
            field=models.CharField(blank=True, max_length=50, verbose_name='fax'),
        ),
        migrations.AddField(
            model_name='soc',
            name='mobile',
            field=models.CharField(blank=True, max_length=30, verbose_name='mobile'),
        ),
        migrations.AddField(
            model_name='soc',
            name='name1',
            field=models.CharField(blank=True, max_length=50, verbose_name='name1'),
        ),
        migrations.AddField(
            model_name='soc',
            name='name2',
            field=models.CharField(blank=True, max_length=100, verbose_name='name2'),
        ),
    ]
