# Generated by Django 4.1.7 on 2023-03-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_soc_name_soc_adress_soc_company_soc_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soc',
            name='email',
            field=models.CharField(blank=True, max_length=100, verbose_name='email'),
        ),
    ]
