# Generated by Django 4.1.7 on 2023-03-31 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Item name')),
                ('price', models.PositiveBigIntegerField(blank=True, verbose_name='price item')),
                ('img', models.ImageField(blank=True, upload_to='images', verbose_name='Item image')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Item slug')),
                ('brand', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='brend_i', to='main.brand')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='cat', to='main.category')),
                ('subcat', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='main.subcategory')),
            ],
        ),
    ]
