# Generated by Django 4.1.7 on 2023-03-31 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_features_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeSlider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='HomeSlider name1')),
                ('name2', models.CharField(max_length=60, verbose_name='HomeSlider name2')),
                ('text', models.TextField(verbose_name='HomeSlider text')),
                ('img', models.ImageField(upload_to='images', verbose_name='HomeSlider image')),
                ('logo', models.ImageField(upload_to='images', verbose_name='HomeSlider logo')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSliderActive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=60, verbose_name='HomeSliderActive name1')),
                ('name2', models.CharField(max_length=60, verbose_name='HomeSliderActive name2')),
                ('text', models.TextField(verbose_name='HomeSliderActive text')),
                ('img', models.ImageField(upload_to='images', verbose_name='HomeSlider image')),
                ('logo', models.ImageField(upload_to='images', verbose_name='HomeSlider logo')),
            ],
        ),
    ]
